// app/layout.tsx
import { ReactNode } from 'react';
import { Inter, Roboto_Mono } from 'next/font/google'; // Google Fonts import
import './globals.css'; // Ensure global styles are imported
import SessionWrapper from './providers/SessionWrapper';
const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const robotoMono = Roboto_Mono({
  variable: '--font-roboto-mono',
  subsets: ['latin'],
});

// Metadata for the page
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${robotoMono.variable} antialiased`}
        suppressHydrationWarning={true} // Prevent hydration warning if necessary
      >
        <SessionWrapper>    
               {children}
        </SessionWrapper>
      </body>
    </html>
  );
}
